### ISSUE TITLE
Please consider adding a license file

### ISSUE THREAD

**Issue by jay-jlm** [andrewrk/pillagers#1]
Please consider adding a license for code and assets.
Other than  package.json mentioning the BSD license, I was unable to find a more detailed licensing information.
Thank you.

**Comment by andrewrk** [comment]
Hey thanks for the interest. I'll add a license file. Everything is freeeeeeeee
I got a lot of it from opengameart.org, and I made some of it myself and then submitted it to opengameart.org. Such as: http://opengameart.org/content/electrical-disintegration-animation
